version: '2'

services:

  demo-xpy:
    container_name: demo-xpy
    hostname: demo-xpy
    image: demo/xpy:latest
    network_mode: host
    tty: true
    environment:
    # if running on-premise, start up the X-Ray daemon with XRAY_DAEMON_ENABLED=1 and disable it with XRAY_DAEMON_ENABLED=0
    - XRAY_DAEMON_ENABLED=1
    # this is the tracking identifier for all data sent to AWS X-Ray
    - XRAY_SERVICE_NAME=demo-xpy
    - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    # silent with: VERBOSE=0 and debug with: VERBOSE=1
    - VERBOSE=0
    volumes:
    - .:/opt/stack
    entrypoint: >
      /bin/bash -c '
      /opt/stack/bin/init.sh
      '
