name: Continuous Build
on: [push, pull_request]

jobs:
  build:
    name: Build Python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [2.7, 3.4, 3.5, 3.6, 3.7, 3.8]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install tox tox-gh-actions
      - name: Test with tox
          run: tox
          env:
            PLATFORM: ${{ matrix.os }}