name: Continuous monitoring of distribution channels
on:
  workflow_dispatch:
  schedule:
    - cron:  '*/10 * * * *'

permissions:
  id-token: write
  contents: read

jobs:
  smoke-tests:
    name: Run smoke tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 #v3.6.0
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a #v4.3.1
        with:
          role-to-assume: ${{ secrets.AWS_INTEG_TEST_ROLE_ARN }}
          aws-region: us-east-1
      
      - uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c #v4.9.1
        with:
          python-version: '3.x'
      
      - run: pip install tox
      
      - name: Run smoke tests
        id: distribution-availability
        run: tox -c tox-distributioncheck.ini
        
      - name: Publish metric on X-Ray Python SDK distribution availability
        if: ${{ always() }}
        run: |
          if [[ "${{ steps.distribution-availability.outcome }}" == "failure" ]]; then
            aws cloudwatch put-metric-data --metric-name XRayPythonSDKDistributionUnavailability --dimensions failure=rate --namespace MonitorSDK --value 1 --timestamp $(date +%s)
          else
            aws cloudwatch put-metric-data --metric-name XRayPythonSDKDistributionUnavailability --dimensions failure=rate --namespace MonitorSDK --value 0 --timestamp $(date +%s)
          fi
